sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker


before_intsall:
  - docker build rpandir1/docker-react -f dockerfile.dev .


script:
  - docker run -e CI=true rpandir1/docker-react npm run test -- --coverage
