sudo: requird
language: node_js
language: node_js
node_js:
  - "8"
services:
  - docker

before_install:
  - docker build -t rpandir1/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true rpandir1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-3"
  bucket_name: "elasticbeanstalk-us-east-2-293021273703"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

